"""
crochet_env.py  —  procedural granny-square environment.

You do not edit this file. The taste/palette decisions live in rules.py.

# How it works

Round 0 is a magic ring (auto-emitted). Each agent round = 4 steps:
  step 1: ROW TYPE   (cluster | stitch)         — constrained by position
  step 2: BODY        (which cluster / stitch)
  step 3: SIDE GAP    (chains between clusters on a side, 1..5)
  step 4: CORNER GAP  (chains at a corner, 1..5)

The env then writes the round's CrochetPARADE source via rules.build_row,
sizing growth (4*round clusters), labels, and chain widths by construction —
so every output parses.

# Row-type constraints (the agent still "picks", but the env overrides where
# the structure is fixed):

  * Round 1 is forced to the opening-block mode.
  * The OPENING BLOCK = first ceil(25%) of rounds is forced to one mode,
    chosen once per square: 50% "stitch", 50% "cluster".
  * If the opening block was STITCH-only, the next two rounds are forced
    transition rows: round_cluster, then square. After that the agent is free.
  * The very last round, if the agent picks "stitch", keeps corner gap >= 2.

# Observation

[round_progress, phase, opening_is_stitch, prev_was_stitch,
 one-hot(last row_type), one-hot(last body), one-hot(last side gap),
 one-hot(last corner gap)]
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Optional

import gymnasium as gym
import numpy as np
from gymnasium import spaces

from parser_client import ParserClient
import rules


# ---------------------------------------------------------------------------
def _opening_block_len(target_rounds: int) -> int:
    """First 25% of the square (at least 1 round)."""
    return max(1, math.ceil(0.25 * target_rounds))


# ---------------------------------------------------------------------------
@dataclass
class EnvConfig:
    target_rounds: int = 4
    difficulty: str = "medium"
    custom_bodies: list = field(default_factory=list)
    reward_overrides: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
class CrochetGrannyEnv(gym.Env):
    metadata = {"render_modes": []}

    PHASE_ROWTYPE = 0
    PHASE_BODY = 1
    PHASE_SIDE = 2
    PHASE_CORNER = 3

    def __init__(self, parser: ParserClient, cfg: EnvConfig):
        super().__init__()
        self._parser = parser
        self._cfg = cfg

        for k, v in cfg.reward_overrides.items():
            if k in rules.REWARDS:
                rules.REWARDS[k] = float(v)

        self._bodies = rules.get_body_stitches(
            cfg.difficulty, getattr(cfg, "custom_bodies", None))
        self._gaps = rules.get_gap_choices(cfg.difficulty)
        self._row_types = rules.get_row_types()
        self._n_bodies = len(self._bodies)
        self._n_gaps = len(self._gaps)
        self._n_rowtypes = len(self._row_types)

        # Flat action space: [row_types][bodies][gaps][gaps]
        self._vocab_size = (self._n_rowtypes + self._n_bodies
                            + self._n_gaps + self._n_gaps)
        self.action_space = spaces.Discrete(self._vocab_size)

        self._obs_dim = (4 + self._n_rowtypes + self._n_bodies
                         + self._n_gaps + self._n_gaps)
        self.observation_space = spaces.Box(
            low=0.0, high=1.0, shape=(self._obs_dim,), dtype=np.float32)

        self._init_episode_state()
        self.last_episode_reward = 0.0
        self.last_episode_pattern = ""
        self.previous_episode_reward = 0.0
        self.previous_episode_pattern = ""

    def _init_episode_state(self):
        self._round = 0
        self._phase = self.PHASE_ROWTYPE
        self._pending_rowtype: Optional[str] = None
        self._pending_body: Optional[str] = None
        self._pending_side: Optional[int] = None
        self._last_rowtype: Optional[str] = None
        self._last_body: Optional[str] = None
        self._last_side: Optional[int] = None
        self._last_corner: Optional[int] = None
        self._committed_lines: list[str] = []
        self._choices: list[dict] = []
        self._prev_cs: list[str] = []
        self._prev_st: list[str] = []
        self._prev_type: str = "ring"
        self._terminated = False
        self._truncated = False
        self._opening_is_stitch = False

    # ---- gym API ----------------------------------------------------------

    def reset(self, *, seed: Optional[int] = None, options=None):
        super().reset(seed=seed)
        self.previous_episode_reward = self.last_episode_reward
        self.previous_episode_pattern = self.last_episode_pattern
        self._init_episode_state()
        self.last_episode_reward = 0.0
        self.last_episode_pattern = ""

        # Flip the opening-block mode coin once per square.
        self._opening_is_stitch = bool(self.np_random.random() < 0.5)

        self._emit_ring()
        return self._observation(), {}

    def step(self, action: int):
        if self._terminated or self._truncated:
            return self._observation(), 0.0, self._terminated, self._truncated, {}

        action = int(action) % self._vocab_size

        rt0 = 0
        rt1 = self._n_rowtypes
        b0 = rt1
        b1 = b0 + self._n_bodies
        s0 = b1
        s1 = s0 + self._n_gaps
        c0 = s1
        c1 = c0 + self._n_gaps

        in_rt = rt0 <= action < rt1
        in_b = b0 <= action < b1
        in_s = s0 <= action < s1
        in_c = c0 <= action < c1

        if self._phase == self.PHASE_ROWTYPE:
            penalty = 0.0 if in_rt else -0.25
            idx = (action - rt0) % self._n_rowtypes
            self._pending_rowtype = self._row_types[idx]
            self._phase = self.PHASE_BODY
            return self._observation(), penalty, False, False, {
                "phase": "row_type", "picked": self._pending_rowtype}

        if self._phase == self.PHASE_BODY:
            penalty = 0.0 if in_b else -0.25
            idx = (action - b0) % self._n_bodies
            self._pending_body = self._bodies[idx]
            self._phase = self.PHASE_SIDE
            return self._observation(), penalty, False, False, {
                "phase": "body", "picked": self._pending_body}

        if self._phase == self.PHASE_SIDE:
            penalty = 0.0 if in_s else -0.25
            idx = (action - s0) % self._n_gaps
            self._pending_side = self._gaps[idx]
            self._phase = self.PHASE_CORNER
            return self._observation(), penalty, False, False, {
                "phase": "side_gap", "picked": self._pending_side}

        # PHASE_CORNER — commit the round.
        penalty = 0.0 if in_c else -0.25
        idx = (action - c0) % self._n_gaps
        corner_gap = self._gaps[idx]
        self._commit_round(self._pending_rowtype, self._pending_body,
                           self._pending_side, corner_gap)
        self._pending_rowtype = None
        self._pending_body = None
        self._pending_side = None
        self._phase = self.PHASE_ROWTYPE

        if self._round >= self._cfg.target_rounds:
            return self._finish_episode()
        return self._observation(), penalty, False, False, {
            "phase": "corner_gap", "round": self._round}

    # ---- internals --------------------------------------------------------

    def _emit_ring(self) -> None:
        self._committed_lines.append(rules._build_ring())
        self._round = 0
        self._prev_cs = []
        self._prev_st = ["R"]
        self._prev_type = "ring"
        self._choices.append({
            "round": 0, "body": "ring", "row_type": "ring",
            "side_gap": 0, "corner_gap": 0, "n_clusters": 0,
            "is_transition": False, "is_last": False,
        })

    def _resolve_row_type(self, round_num: int, requested: str) -> str:
        """Every round is a COLUMN row now. Stitch-only rows and the
        round_cluster / square transition rows have been removed, so the
        opening-block coin and the transition machinery no longer fire — we
        always resolve to a single column row type ("cluster")."""
        return "cluster"

    def _commit_round(self, row_type: str, body: str,
                      side_gap: int, corner_gap: int) -> None:
        round_num = self._round + 1
        is_last = (round_num >= self._cfg.target_rounds)

        resolved = self._resolve_row_type(round_num, row_type)

        # Last row, if a stitch row, must keep corner gap >= 2.
        if is_last and resolved == "stitch":
            corner_gap = max(2, corner_gap)

        n_clusters = rules.cluster_count_for_round(round_num)

        ctx = rules.RowCtx(
            round_num=round_num,
            row_type=resolved,
            body=body,
            side_gap=side_gap,
            corner_gap=corner_gap,
            n_clusters=n_clusters,
            prev_cs=self._prev_cs,
            prev_st=self._prev_st,
            prev_type=self._prev_type,
        )
        line, new_cs, new_st = rules.build_row(ctx)

        self._committed_lines.append(line)
        self._round = round_num
        self._prev_cs = new_cs
        self._prev_st = new_st
        self._prev_type = resolved
        self._last_rowtype = resolved
        self._last_body = body
        self._last_side = side_gap
        self._last_corner = corner_gap

        self._choices.append({
            "round": round_num,
            "body": body,
            "row_type": resolved,
            "side_gap": side_gap,
            "corner_gap": corner_gap,
            "n_clusters": n_clusters,
            "is_transition": resolved in ("round_cluster", "square"),
            "is_last": is_last,
        })

    def _finish_episode(self):
        pattern = "\n".join(self._committed_lines)
        verdict = self._parser.evaluate(pattern)
        reward = float(rules.score(
            pattern=pattern, verdict=verdict, choices=self._choices,
            target_rounds=self._cfg.target_rounds,
            difficulty=self._cfg.difficulty))
        if not verdict.ok:
            reward = -50.0

        self.last_episode_reward = reward
        self.last_episode_pattern = pattern
        self._terminated = True
        return self._observation(), reward, True, False, {
            "pattern": pattern,
            "parse_ok": bool(verdict.ok),
            "n_stitches": int(verdict.n_stitches),
            "rounds": self._round,
            "choices": self._choices,
            "reward": reward,
        }

    # ---- observation ------------------------------------------------------

    def _observation(self) -> np.ndarray:
        obs = np.zeros(self._obs_dim, dtype=np.float32)
        obs[0] = self._round / max(1, self._cfg.target_rounds)
        obs[1] = float(self._phase) / 3.0
        obs[2] = 1.0 if self._opening_is_stitch else 0.0
        obs[3] = 1.0 if self._prev_type == "stitch" else 0.0
        base = 4
        if self._last_rowtype in self._row_types:
            obs[base + self._row_types.index(self._last_rowtype)] = 1.0
        base += self._n_rowtypes
        if self._last_body in self._bodies:
            obs[base + self._bodies.index(self._last_body)] = 1.0
        base += self._n_bodies
        if self._last_side in self._gaps:
            obs[base + self._gaps.index(self._last_side)] = 1.0
        base += self._n_gaps
        if self._last_corner in self._gaps:
            obs[base + self._gaps.index(self._last_corner)] = 1.0
        return obs

    # ---- public introspection --------------------------------------------

    @property
    def current_pattern(self) -> str:
        return "\n".join(self._committed_lines)


# ---------------------------------------------------------------------------
VOCABS = {
    k: (rules.get_row_types() + rules.get_body_stitches(k)
        + [f"side{g}" for g in rules.get_gap_choices(k)]
        + [f"corner{g}" for g in rules.get_gap_choices(k)])
    for k in rules.BODY_BY_DIFFICULTY.keys()
}


# Legacy alias — train_server.py imports CrochetTokenEnv.
CrochetTokenEnv = CrochetGrannyEnv